### ISSUE TITLE
Add token: BrahmaOS(BRM)

### ISSUE THREAD

**Issue by stevenocean** [Loopring/token-listing#5]
# Registration

```
Token Spec: ERC20
Smart contract address: https://etherscan.io/token/0xd7732e3783b0047aa251928960063f863ad022d8
Website: https://www.brahmaos.io
Email: admin@brahmaos.io
```

If your token's source code has not been verified, please provide the following:

```
Digits: 18
Name: BrahmaOS
Symbol: BRM
```

## Listed by Loopr Wallet (loopring.io)

Do you want your token to be added to Loopr Wallet? YES

## Trading Pair

Specify your desired trading pairs:

```
BRM/ETH
BRM/LRC
BRM/QTUM
```

**Comment by stevenocean** [comment]
Why not support our BRM token? @dong77

**Comment by kongliangzhong** [comment]
listed in batch#10
