### ISSUE TITLE
Add token: Marcelo (MRL)

### ISSUE THREAD

**Issue by MarceloMRL** [Loopring/token-listing#8]
Registration
Token Spec: ERC20 
Smart contract address: https://etherscan.io/address/0x82125afe01819dff1535d0d6276d57045291b6c0[]
Website: [https://www.marcelo-mrl.com/]
Email: [info@marcelo-mrl.com]

Listed by Loopr Wallet (loopring.io)
Do you want your token to be added to Loopr Wallet? YES

Trading Pair
Specify your desired trading pairs:

[MRL]/ETH
[MRL]/LRC
[MRL]/QTUM

**Comment by kongliangzhong** [comment]
listed in batch#10
