### ISSUE TITLE
Add token: Trend Network (TRD)

### ISSUE THREAD

**Issue by toyovoke** [Loopring/token-listing#9]
Token Spec: ERC20
Smart contract address: https://etherscan.io/address/0xc879041033702169164a967ebf4d770cc5875a8b
Website: https://trendnetwork.online/
Email: trendnetworktoken@gmail.com

Trading Pair
TRD/ETH
TRD/LRC
TRD/QTUM

**Comment by kongliangzhong** [comment]
website not exist.
